# Site settings
title: Perú Jenkins Area Meetup
email: jenkins.peru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Comunidad de Jenkins para Perú.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jenkinsperu.github.io" # the base hostname & protocol for your site
twitter_username: JenkinsPeru
github_username:  jenkinsperu

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
